ALTER TABLE "FilamentSpool"
ADD COLUMN "startingGrams" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN "rollCostCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "assignedPrinterHistory" JSONB NOT NULL DEFAULT '[]';
