import { describe, expect, it } from "vitest";
import {
  buildCentauriPrinterFilename,
  buildCentauriTimelapseEnableRequest,
  buildCentauriTimelapseExportRequest,
  buildCentauriStartPrintRequest,
  describeCentauriStartAck,
  findCentauriFile,
  getCentauriResponseAck,
  isCentauriIdleStatus,
  ManualNoopPrinterControlAdapter,
  prepareCentauriTimelapseGcode,
  resolveCentauriUploadUrl
} from "./printer-control";

describe("printer control adapter", () => {
  it("acknowledges start commands without calling real printer APIs", async () => {
    const adapter = new ManualNoopPrinterControlAdapter();

    await expect(
      adapter.startPrint({
        printJobId: "job_1",
        gcodeLocalPath: "/data/node-jobs/job_1.gcode"
      })
    ).resolves.toEqual({
      acknowledged: true,
      mode: "manual-noop",
      message: "Manual/no-op adapter acknowledged start command; no printer API was called."
    });
  });

  it("acknowledges maintenance safety commands without calling real printer APIs", async () => {
    const adapter = new ManualNoopPrinterControlAdapter();

    await expect(adapter.stopPrint("job_1")).resolves.toMatchObject({
      acknowledged: true,
      mode: "manual-noop"
    });
    await expect(adapter.cooldown("printer_1")).resolves.toMatchObject({
      acknowledged: true,
      mode: "manual-noop"
    });
  });

  it("builds Centauri upload and start-print commands with timelapse armed", () => {
    expect(resolveCentauriUploadUrl("ws://192.168.10.125:3030/websocket")).toBe("http://192.168.10.125:3030/uploadFile/upload");
    expect(buildCentauriPrinterFilename("/data/sliced/dragon.gcode")).toBe("dragon.gcode");
    expect(buildCentauriStartPrintRequest({ filename: "dragon.gcode", mainboardId: "mainboard-1", requestId: "12345", timestamp: 1778774100000 })).toEqual({
      Id: "mainboard-1",
      Data: {
        Cmd: 128,
        Data: {
          Filename: "dragon.gcode",
          StartLayer: 0,
          Calibration_switch: 0,
          PrintPlatformType: 0,
          Tlp_Switch: 1,
          slot_map: []
        },
        RequestID: "12345",
        MainboardID: "mainboard-1",
        TimeStamp: 1778774100000,
        From: 1
      },
      Topic: ""
    });
  });

  it("builds Centauri timelapse enable and export commands", () => {
    expect(buildCentauriTimelapseEnableRequest({ mainboardId: "mainboard-1", requestId: "12346", timestamp: 1778774100001 })).toEqual({
      Id: "mainboard-1",
      Data: {
        Cmd: 387,
        Data: { Enable: 1 },
        RequestID: "12346",
        MainboardID: "mainboard-1",
        TimeStamp: 1778774100001,
        From: 1
      },
      Topic: ""
    });
    expect(buildCentauriTimelapseExportRequest({ path: "/local/aic_tlp/dragon.mp4", mainboardId: "mainboard-1", requestId: "12347", timestamp: 1778774100002 })).toEqual({
      Id: "mainboard-1",
      Data: {
        Cmd: 323,
        Data: { Url: ["/local/aic_tlp/dragon.mp4"] },
        RequestID: "12347",
        MainboardID: "mainboard-1",
        TimeStamp: 1778774100002,
        From: 1
      },
      Topic: ""
    });
  });

  it("adds Centauri layer stats to Orca-style gcode before upload when missing", () => {
    const gcode = [
      "; generated by OrcaSlicer",
      "G28",
      ";LAYER_CHANGE",
      ";Z:0.2",
      "G1 X1",
      ";LAYER_CHANGE",
      ";Z:0.4",
      "G1 X2"
    ].join("\n");

    expect(prepareCentauriTimelapseGcode(Buffer.from(gcode)).toString()).toContain("SET_PRINT_STATS_INFO TOTAL_LAYER=2");
    expect(prepareCentauriTimelapseGcode(Buffer.from(gcode)).toString()).toContain("SET_PRINT_STATS_INFO CURRENT_LAYER=1");
    expect(prepareCentauriTimelapseGcode(Buffer.from(gcode)).toString()).toContain("SET_PRINT_STATS_INFO CURRENT_LAYER=2");
  });

  it("parses Centauri response ACK codes from nested protocol messages", () => {
    expect(getCentauriResponseAck({ Data: { Cmd: 128, Data: { Ack: 0 } } }, 128)).toBe(0);
    expect(getCentauriResponseAck({ Data: { Cmd: 128, Data: { Ack: 2 } } }, 128)).toBe(2);
    expect(getCentauriResponseAck({ Data: { Cmd: 258, Data: { Ack: 0 } } }, 128)).toBeNull();
    expect(describeCentauriStartAck(2)).toBe("not found");
  });

  it("detects idle status and uploaded files before allowing automatic start", () => {
    expect(isCentauriIdleStatus({ Status: { CurrentStatus: 0, PrintInfo: { Status: 0, ErrorNumber: 0 } } })).toBe(true);
    expect(isCentauriIdleStatus({ Status: { CurrentStatus: [0], PrintInfo: { Status: 0, ErrorNumber: 0 } } })).toBe(true);
    expect(isCentauriIdleStatus({ Status: { CurrentStatus: 1, PrintInfo: { Status: 1, ErrorNumber: 0 } } })).toBe(false);
    expect(isCentauriIdleStatus({ Status: { CurrentStatus: 0, PrintInfo: { Status: 0, ErrorNumber: 2 } } })).toBe(false);
    expect(
      findCentauriFile(
        {
          Data: {
            Cmd: 258,
            Data: {
              Ack: 0,
              FileList: [{ name: "/local//dragon.gcode", usedSize: 1234, type: 1 }]
            }
          }
        },
        "/local//dragon.gcode"
      )
    ).toEqual({ name: "/local//dragon.gcode", usedSize: 1234, type: 1 });
    expect(
      findCentauriFile(
        {
          Data: {
            Cmd: 258,
            Data: {
              Ack: 0,
              FileList: [{ name: "/local//dragon.gcode", usedSize: 1234, type: 1 }]
            }
          }
        },
        "dragon.gcode"
      )
    ).toEqual({ name: "/local//dragon.gcode", usedSize: 1234, type: 1 });
  });
});
