ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "colorSlotCount" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "CartItem"
ADD COLUMN IF NOT EXISTS "selectedFilamentMaterialIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "selectedColors" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "selectedFilamentMaterialIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "selectedColors" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "OrderItem"
ADD COLUMN IF NOT EXISTS "selectedFilamentMaterialIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "selectedColors" JSONB NOT NULL DEFAULT '[]';
