ALTER TABLE "Order"
  ADD COLUMN "fulfillmentMethod" TEXT NOT NULL DEFAULT 'SHIP',
  ADD COLUMN "shippingName" TEXT,
  ADD COLUMN "shippingStreet1" TEXT,
  ADD COLUMN "shippingStreet2" TEXT,
  ADD COLUMN "shippingCity" TEXT,
  ADD COLUMN "shippingState" TEXT,
  ADD COLUMN "shippingZip" TEXT,
  ADD COLUMN "shippingCountry" TEXT DEFAULT 'US',
  ADD COLUMN "shippingPhone" TEXT,
  ADD COLUMN "shippingEmail" TEXT,
  ADD COLUMN "shippoShipmentId" TEXT,
  ADD COLUMN "shippoRateId" TEXT,
  ADD COLUMN "shippoTransactionId" TEXT,
  ADD COLUMN "shippingProvider" TEXT,
  ADD COLUMN "shippingService" TEXT,
  ADD COLUMN "shippingRateCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "shippingAmountCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "shippingLabelUrl" TEXT,
  ADD COLUMN "trackingNumber" TEXT,
  ADD COLUMN "trackingUrl" TEXT,
  ADD COLUMN "labelPrintedAt" TIMESTAMP(3);
